[workspace]
members = ["./services/authcore", "./services/auditlog", "./services/platform", "./services/webhook", "./services/messaging", "prisma-cli"]
resolver = "2"

[workspace.dependencies]
crypto = { path = "./crypto" }
