[workspace]
members = [
    "./services/authcore",
    "./services/auditlog",
    "./services/platform",
    "./services/webhook",
    "./misc/prisma-cli",
    "./testing"
]
resolver = "2"

[workspace.dependencies]
crypto = { path = "./misc/crypto" }
